Make sure the file is not open anymore
From time to time, we observe this error:

INFO:PumaGuard:New file detected: /mnt/c/pumaguard/classification/A25041806114111.jpg
Exception in thread Thread-111 (_handle_new_file):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hvisw/.local/share/pipx/venvs/pumaguard/lib/python3.12/site-packages/pumaguard/server.py", line 134, in _handle_new_file
    prediction = classify_image(self.presets, self.model, filepath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hvisw/.local/share/pipx/venvs/pumaguard/lib/python3.12/site-packages/pumaguard/utils.py", line 242, in classify_image
    img = Image.open(image_path).convert('RGB')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hvisw/.local/share/pipx/venvs/pumaguard/lib/python3.12/site-packages/PIL/Image.py", line 982, in convert
    self.load()
  File "/home/hvisw/.local/share/pipx/venvs/pumaguard/lib/python3.12/site-packages/PIL/ImageFile.py", line 386, in load
    raise OSError(msg)
OSError: image file is truncated (3 bytes not processed)

The root cause is presumably that the FTP server is still writing to the
image file when pumaguard picks it up. This leads to the file being
incomplete.

This change adds a check to see whether any process has an open file
descriptor for the new file before proceeding with processing the file.

Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>